### PR TITLE
use goop for dependencies

### PR DESCRIPTION
**Pull request by nikolaiwarner**

### CODE REVIEW

**Comment by chaserx** [comment]
I guess we have to have both git and mercurial installed for goop to work. You experience this?

``` bash
chase at foxy in ~/code/streakers (on take_params_return_json ✔) using 2.1.4
± go get github.com/nitrous-io/goop

go: missing Mercurial command. See http://golang.org/s/gogetcmd
package code.google.com/p/go.tools/go/vcs: exec: "hg": executable file not found in $PATH
```

**Comment by chaserx** [comment]
+1

**Comment by chaserx** [comment]
rebase

**Comment by chaserx** [comment]
lgtm

**Comment by nikolaiwarner** [comment]
fixes #8

**Pull request merged**
